### ISSUE TITLE
Benefits over other packages?

### ISSUE THREAD

**Issue by ramonsmits** [at0dd/tesla-api#1]
There are already a few packages. What is the difference with https://github.com/razfriman/TeslaLib/ or https://github.com/JSkimming/tesla-net besides targeting .net 5 which you could also do with those projects?

**Comment by at0dd** [comment]
I haven't taken a close look at those two, but probably not much. It's been 1+ years since either nuget package has been updated. My goal with this repo is to make it easy to use, document well, and keep up to date with [timdorr/tesla-api](https://github.com/timdorr/tesla-api) as much as possible.

**Comment by ramonsmits** [comment]
@at0dd The dependencies are less to that is plus. Do you have all API's implemented at the moment?

**Comment by at0dd** [comment]
All of the vehicle state and commands are implemented.
