### ISSUE TITLE
Nullable Field Error on Deserialize

### ISSUE THREAD

**Issue by HYLETE-REPO** [at0dd/tesla-api#32]
Hi,
Hope it is ok to posts errors here.

I just updated to 1.06. Calling GetVehicleDataAsync I receive the following error:
Error converting value {null} to type 'System.Boolean'. Path 'response.charge_state.trip_charging', line 1, position 2176.

Thanks.

**Comment by at0dd** [comment]
Hey thanks! I'll get a PR in soon.
