### ISSUE TITLE
ChargeAmps is missing from ChargeState and exceptions with reply from GetVehicleState

### ISSUE THREAD

**Issue by tagevm** [at0dd/tesla-api#34]
Nice job with the api, I found a few issues:

ChargeState is missing ChargeAmps property
Numerous properties should be nullable
MinimumLimitMilesPerHour should be null

**Comment by tagevm** [comment]
Actually, I have solved the issue locally, but I don't seem to be able to figure out how to create a branch and submit a pull request

**Comment by claudiosanchez** [comment]
You will first want to fork the repo, and then submit a pull request. I hope this helps. @tagevm. 


https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
