### ISSUE TITLE
Tesla not returning location data by default

### ISSUE THREAD

**Issue by MischaWeerwag** [at0dd/tesla-api#83]
https://developer.tesla.com/docs/fleet-api#vehicle_data

2023-10-24: Vehicle data update on firmware versions 2023.38+

Vehicles running firmware versions 2023.38+ will not return location information by default in vehicle data. Developers who need that information will need to add "location_data" parameter to the query, see [here](https://developer.tesla.com/docs/fleet-api#vehicle_data). This will result in a location sharing icon to show on the vehicle UI.

Important: Fetching vehicle data periodically is not recommended, check out [Fleet Telemetry](https://github.com/teslamotors/fleet-telemetry) for streaming needs.

We should add this ?endpoints=location_data to GET /api/1/vehicles/{id}/vehicle_data for backward compatibility 👯 

https://github.com/at0dd/tesla-api/pull/84 NOT TESTED

**Comment by MischaWeerwag** [comment]
Tested latest commit, which adds all possible endpoint to give backward compatibility.

**Comment by at0dd** [comment]
Merged!
